### ISSUE TITLE
Which Blockfrost network to use?

### ISSUE THREAD

**Issue by peterVG** [Python-Cardano/pycardano#112]
I'm getting 404 errors from the Blockfrost API when trying to implement the [Transaction builder example code](https://github.com/Python-Cardano/pycardano/blob/main/examples/tx_builder.py). 

 Can you please clarify which network my Blockfrost project should be using to sync with the pyCardano network.TESTNET option? There's a choice between Testnet, Preprod, and Preview
<img width="277" alt="Screen Shot 2022-10-27 at 1 27 27 PM" src="https://user-images.githubusercontent.com/672121/198391659-95fc28d6-2e48-41bf-a1b6-3f818c2457c3.png">

**Comment by cffls** [comment]
Only use `network.MAINNET` for Cardano mainnet, the rest of networks should use `network.TESTNET`.

For testnet, you should specify network url like this example below:

```python
from pycardano import BlockFrostChainContext, Network

chain_context = BlockFrostChainContext(
    project_id="YOUR_BLOCKFROST_PROJECT_ID",
    network=Network.TESTNET,
    base_url="https://cardano-preprod.blockfrost.io/api", # <--- this is important
)
```

The transaction builder example is outdated and not very accurate because of recent introduction of preview and preprod network. Will try to fix it.

**Comment by peterVG** [comment]
super, thanks.
