### ISSUE TITLE
Example on transaction builder doesn't provide some detail

### ISSUE THREAD

**Issue by cokariinc** [Python-Cardano/pycardano#17]
**Describe the bug**
A wonderful package i must say, the issue I have right now is with the example on using the transaction builder. 

**To Reproduce**
This block shows how to add an output but the comment is confusing
```
builder.add_output(
    TransactionOutput(
        address,
        Value.from_primitive(
            [
                2000000,
                {
                    bytes.fromhex(
                        "57fca08abbaddee36da742a839f7d83a7e1d2419f1507fcbf3916522"
                    ): {  # Policy ID
                        b"CHOC": 200
                    }
                },
            ]
        ),
    )
)
```
is the _b"CHOC"_ part the policy-id or "57fca08abbaddee36da742a839f7d83a7e1d2419f1507fcbf3916522". Whichever it is, what exactly is the other?

**Comment by cffls** [comment]
Hi, 

Thanks for reporting the issue. Comments in the code are confusing indeed. It was probably caused by a reformat in the past. The policy id in this example is `"57fca08abbaddee36da742a839f7d83a7e1d2419f1507fcbf3916522"`, and `b"CHOC"` is name of the asset. I just fixed the example in this commit: https://github.com/cffls/pycardano/commit/ee037a3041d104bea7192cf416c7b8c5b69ad430.
